interface EmojiEntry {
  emoji: string;
  nombre: string;
  keywords: string[];
}

const categorias: { id: string; label: string; icono: string }[] = [
  { id: 'smileys', label: 'Personas', icono: '😀' },
  { id: 'animales', label: 'Animales', icono: '🐻' },
  { id: 'comida', label: 'Comida', icono: '🍎' },
  { id: 'actividades', label: 'Actividades', icono: '🏀' },
  { id: 'casa', label: 'Casa', icono: '🏠' },
  { id: 'viajes', label: 'Viajes', icono: '🚗' },
  { id: 'simbolos', label: 'Símbolos', icono: '💎' },
  { id: 'musica', label: 'Arte', icono: '🎵' },
];

const emojis: Record<string, EmojiEntry[]> = {
  smileys: [
    { emoji: '😀', nombre: 'sonrisa', keywords: ['feliz', 'alegre', 'contento'] },
    { emoji: '😃', nombre: 'sonrisa grande', keywords: ['feliz', 'alegre'] },
    { emoji: '😄', nombre: 'sonrisa ojos', keywords: ['feliz', 'contento'] },
    { emoji: '😁', nombre: 'sonrisa dientes', keywords: ['feliz', 'alegre'] },
    { emoji: '😅', nombre: 'sonrisa sudor', keywords: ['nervioso', 'risa'] },
    { emoji: '😂', nombre: 'llanto risa', keywords: ['risa', 'divertido'] },
    { emoji: '🤣', nombre: 'rodar risa', keywords: ['risa', 'divertido'] },
    { emoji: '😊', nombre: 'sonrisa ojos cerrados', keywords: ['feliz', 'contento'] },
    { emoji: '😇', nombre: 'angel', keywords: ['inocente', 'bondad'] },
    { emoji: '🙂', nombre: 'sonrisa leve', keywords: ['feliz', 'tranquilo'] },
    { emoji: '😉', nombre: 'guiño', keywords: ['picaro', 'complice'] },
    { emoji: '😌', nombre: 'aliviado', keywords: ['relajado', 'paz'] },
    { emoji: '😍', nombre: 'ojos corazon', keywords: ['amor', 'gusto'] },
    { emoji: '🥰', nombre: 'corazones', keywords: ['amor', 'enamorado'] },
    { emoji: '😘', nombre: 'beso', keywords: ['amor', 'cariño'] },
    { emoji: '😗', nombre: 'beso simple', keywords: ['amor'] },
    { emoji: '😋', nombre: 'rico', keywords: ['comida', 'delicioso'] },
    { emoji: '😛', nombre: 'lengua', keywords: ['burla', 'divertido'] },
    { emoji: '😜', nombre: 'lengua guiño', keywords: ['burla', 'divertido'] },
    { emoji: '🤪', nombre: 'loco', keywords: ['divertido', 'loco'] },
    { emoji: '😝', nombre: 'lengua ojos', keywords: ['burla', 'divertido'] },
    { emoji: '🤑', nombre: 'dinero', keywords: ['plata', 'rico'] },
    { emoji: '🤗', nombre: 'abrazar', keywords: ['abrazo', 'cariño'] },
    { emoji: '🤔', nombre: 'pensando', keywords: ['pensar', 'duda'] },
    { emoji: '🤐', nombre: 'boca cerrada', keywords: ['silencio', 'secreto'] },
    { emoji: '🤨', nombre: 'ceja levantada', keywords: ['duda', 'esceptico'] },
    { emoji: '😐', nombre: 'neutral', keywords: ['serio', 'normal'] },
    { emoji: '😑', nombre: 'inexpresivo', keywords: ['serio'] },
    { emoji: '😶', nombre: 'sin boca', keywords: ['silencio', 'callado'] },
    { emoji: '😏', nombre: 'sonrisa picara', keywords: ['picaro', 'sarcasmo'] },
    { emoji: '😒', nombre: 'no gusto', keywords: ['disgusto', 'aburrido'] },
    { emoji: '🙄', nombre: 'ojos en blanco', keywords: ['disgusto', 'fastidio'] },
    { emoji: '😬', nombre: 'mueca', keywords: ['nervioso', 'incomodo'] },
    { emoji: '🤥', nombre: 'mentiroso', keywords: ['mentira', 'pinocho'] },
    { emoji: '😌', nombre: 'aliviado', keywords: ['alivio', 'paz'] },
    { emoji: '😔', nombre: 'triste', keywords: ['tristeza', 'pensativo'] },
    { emoji: '😪', nombre: 'somnoliento', keywords: ['sueño', 'cansado'] },
    { emoji: '🤤', nombre: 'babear', keywords: ['sueño', 'hambriento'] },
    { emoji: '😴', nombre: 'dormir', keywords: ['sueño', 'dormido'] },
    { emoji: '😷', nombre: 'mascarilla', keywords: ['enfermo', 'medico'] },
    { emoji: '🤒', nombre: 'termometro', keywords: ['enfermo', 'fiebre'] },
    { emoji: '🤕', nombre: 'venda', keywords: ['herido', 'golpe'] },
    { emoji: '🤢', nombre: 'nausea', keywords: ['enfermo', 'asco'] },
    { emoji: '🤮', nombre: 'vomitar', keywords: ['enfermo', 'asco'] },
    { emoji: '🤧', nombre: 'estornudo', keywords: ['enfermo', 'gripe'] },
    { emoji: '🥵', nombre: 'calor', keywords: ['caliente', 'sudor'] },
    { emoji: '🥶', nombre: 'frio', keywords: ['frio', 'helado'] },
    { emoji: '🥴', nombre: 'mareado', keywords: ['borracho', 'confuso'] },
    { emoji: '😵', nombre: 'ojos cruz', keywords: ['mareado', 'confuso'] },
    { emoji: '🤯', nombre: 'explosion cabeza', keywords: ['sorprendido', 'asombro'] },
    { emoji: '🤠', nombre: 'vaquero', keywords: ['sombrero', 'oeste'] },
    { emoji: '🥳', nombre: 'fiesta', keywords: ['cumpleaños', 'celebrar'] },
    { emoji: '😎', nombre: 'lentes sol', keywords: ['fresco', 'genial'] },
    { emoji: '🤓', nombre: 'nerd', keywords: ['lentes', 'estudioso'] },
    { emoji: '🧐', nombre: 'monoculo', keywords: ['investigar', 'curioso'] },
    { emoji: '😕', nombre: 'confundido', keywords: ['duda', 'confusion'] },
    { emoji: '😟', nombre: 'preocupado', keywords: ['preocupacion', 'nervioso'] },
    { emoji: '🙁', nombre: 'triste leve', keywords: ['triste', 'decepcion'] },
    { emoji: '😮', nombre: 'sorprendido', keywords: ['sorpresa', 'asombro'] },
    { emoji: '😯', nombre: 'asombrado', keywords: ['sorpresa'] },
    { emoji: '😲', nombre: 'asombro total', keywords: ['sorpresa', 'shock'] },
    { emoji: '😳', nombre: 'sonrojado', keywords: ['timido', 'avergonzado'] },
    { emoji: '🥺', nombre: 'ojos suplicantes', keywords: ['suplica', 'tierno'] },
    { emoji: '😢', nombre: 'lagrima', keywords: ['triste', 'llanto'] },
    { emoji: '😭', nombre: 'llanto fuerte', keywords: ['triste', 'llorar'] },
    { emoji: '😤', nombre: 'fumando', keywords: ['enojado', 'frustrado'] },
    { emoji: '😡', nombre: 'enojado rojo', keywords: ['enojo', 'rabia'] },
    { emoji: '🤬', nombre: 'groserias', keywords: ['enojo', 'rabia'] },
    { emoji: '👋', nombre: 'saludar', keywords: ['hola', 'chao'] },
    { emoji: '🤚', nombre: 'mano levantada', keywords: ['alto', 'parar'] },
    { emoji: '✋', nombre: 'mano alta', keywords: ['alto', 'detener'] },
    { emoji: '👌', nombre: 'ok', keywords: ['bien', 'okey'] },
    { emoji: '🤏', nombre: 'pizca', keywords: ['poquito', 'pequeño'] },
    { emoji: '✌️', nombre: 'paz', keywords: ['victoria', 'paz'] },
    { emoji: '🤞', nombre: 'cruzar dedos', keywords: ['suerte', 'esperanza'] },
    { emoji: '🤟', nombre: 'te amo', keywords: ['amor', 'señas'] },
    { emoji: '🤘', nombre: 'cuernos', keywords: ['rock', 'musica'] },
    { emoji: '🤙', nombre: 'llamar', keywords: ['telefono', 'cali'] },
    { emoji: '👈', nombre: 'apuntar izquierda', keywords: ['señalar', 'izquierda'] },
    { emoji: '👉', nombre: 'apuntar derecha', keywords: ['señalar', 'derecha'] },
    { emoji: '👆', nombre: 'apuntar arriba', keywords: ['señalar', 'arriba'] },
    { emoji: '👇', nombre: 'apuntar abajo', keywords: ['señalar', 'abajo'] },
    { emoji: '👍', nombre: 'pulgar arriba', keywords: ['bien', 'megusta', 'aprobado'] },
    { emoji: '👎', nombre: 'pulgar abajo', keywords: ['mal', 'nomegusta'] },
    { emoji: '👊', nombre: 'punio', keywords: ['golpe', 'fuerza'] },
    { emoji: '✊', nombre: 'punio alto', keywords: ['protesta', 'poder'] },
    { emoji: '🤛', nombre: 'punio izq', keywords: ['golpe'] },
    { emoji: '🤜', nombre: 'punio der', keywords: ['golpe'] },
    { emoji: '👏', nombre: 'aplaudir', keywords: ['aplausos', 'felicitar'] },
    { emoji: '🙌', nombre: 'brazos arriba', keywords: ['festejar', 'alegria'] },
    { emoji: '👐', nombre: 'manos abiertas', keywords: ['abrir', 'recibir'] },
    { emoji: '🤲', nombre: 'manos juntas', keywords: ['pedir', 'orar'] },
    { emoji: '🤝', nombre: 'apreton', keywords: ['acuerdo', 'saludo'] },
    { emoji: '🙏', nombre: 'rezar', keywords: ['orar', 'gracias', 'pedir'] },
    { emoji: '💪', nombre: 'bicep', keywords: ['fuerza', 'musculo', 'poder'] },
    { emoji: '🦵', nombre: 'pierna', keywords: ['pierna'] },
    { emoji: '🦶', nombre: 'pie', keywords: ['pie'] },
    { emoji: '👂', nombre: 'oreja', keywords: ['oido', 'escuchar'] },
    { emoji: '👃', nombre: 'nariz', keywords: ['nariz', 'oler'] },
    { emoji: '🧠', nombre: 'cerebro', keywords: ['mente', 'inteligencia'] },
    { emoji: '🫀', nombre: 'corazon organo', keywords: ['corazon', 'vida'] },
    { emoji: '👀', nombre: 'ojos', keywords: ['mirar', 'ver'] },
    { emoji: '👅', nombre: 'lengua', keywords: ['lengua', 'gusto'] },
    { emoji: '👄', nombre: 'boca', keywords: ['boca', 'labios'] },
    { emoji: '👶', nombre: 'bebe', keywords: ['bebe', 'pequeño'] },
    { emoji: '🧒', nombre: 'nino', keywords: ['niño', 'chico'] },
    { emoji: '👦', nombre: 'nino', keywords: ['niño', 'hijo'] },
    { emoji: '👧', nombre: 'nina', keywords: ['niña', 'hija'] },
    { emoji: '🧑', nombre: 'persona', keywords: ['persona', 'adulto'] },
    { emoji: '👨', nombre: 'hombre', keywords: ['hombre', 'papa'] },
    { emoji: '👩', nombre: 'mujer', keywords: ['mujer', 'mama'] },
    { emoji: '🧓', nombre: 'anciano', keywords: ['viejo', 'abuelo'] },
    { emoji: '👴', nombre: 'abuelo', keywords: ['anciano', 'viejo'] },
    { emoji: '👵', nombre: 'abuela', keywords: ['anciana', 'vieja'] },
    { emoji: '👨‍👩‍👧‍👦', nombre: 'familia', keywords: ['familia', 'hogar'] },
    { emoji: '👨‍👩‍👦', nombre: 'familia hijo', keywords: ['familia'] },
    { emoji: '👩‍👦', nombre: 'mama hijo', keywords: ['familia', 'madre'] },
    { emoji: '👨‍👦', nombre: 'papa hijo', keywords: ['familia', 'padre'] },
    { emoji: '👮', nombre: 'policia', keywords: ['policia', 'seguridad'] },
    { emoji: '🕵️', nombre: 'detective', keywords: ['investigador', 'deteccion'] },
    { emoji: '💂', nombre: 'guardia', keywords: ['guardia', 'seguridad'] },
    { emoji: '👷', nombre: 'constructor', keywords: ['obrero', 'casco'] },
    { emoji: '🤴', nombre: 'principe', keywords: ['rey', 'corona'] },
    { emoji: '👸', nombre: 'princesa', keywords: ['reina', 'corona'] },
    { emoji: '👳', nombre: 'turbante', keywords: ['turbante'] },
    { emoji: '👲', nombre: 'gorro chino', keywords: ['chino'] },
    { emoji: '🧕', nombre: 'velo', keywords: ['velo', 'musulman'] },
    { emoji: '🤵', nombre: 'traje', keywords: ['formal', 'novio'] },
    { emoji: '👰', nombre: 'velo novia', keywords: ['novia', 'boda'] },
    { emoji: '🤰', nombre: 'embarazada', keywords: ['embarazo', 'bebe'] },
    { emoji: '🤱', nombre: 'amamantar', keywords: ['bebe', 'leche'] },
    { emoji: '👼', nombre: 'angel bebe', keywords: ['angel', 'bebe'] },
    { emoji: '🎅', nombre: 'santa', keywords: ['navidad', 'santa'] },
    { emoji: '🤶', nombre: 'mama noel', keywords: ['navidad'] },
    { emoji: '🦸', nombre: 'superheroe', keywords: ['heroe', 'superpoder'] },
    { emoji: '🦹', nombre: 'villano', keywords: ['malo', 'enemigo'] },
    { emoji: '🧙', nombre: 'mago', keywords: ['magia', 'hechizo'] },
    { emoji: '🧚', nombre: 'hada', keywords: ['magia', 'fantasia'] },
    { emoji: '🧛', nombre: 'vampiro', keywords: ['vampiro', 'noche'] },
    { emoji: '🧜', nombre: 'sirena', keywords: ['mar', 'mitologico'] },
    { emoji: '🧝', nombre: 'elfo', keywords: ['elfo', 'fantasia'] },
    { emoji: '🧞', nombre: 'genio', keywords: ['magia', 'deseo'] },
    { emoji: '🧟', nombre: 'zombie', keywords: ['zombie', 'muerto'] },
    { emoji: '💆', nombre: 'masaje', keywords: ['relajar', 'spa'] },
    { emoji: '💇', nombre: 'corte pelo', keywords: ['peluqueria', 'peinar'] },
    { emoji: '🚶', nombre: 'caminar', keywords: ['caminar', 'andar'] },
    { emoji: '🧍', nombre: 'parado', keywords: ['parado', 'de pie'] },
    { emoji: '🧎', nombre: 'arrodillado', keywords: ['rodilla', 'orar'] },
    { emoji: '🏃', nombre: 'correr', keywords: ['correr', 'deporte', 'ejercicio'] },
    { emoji: '💃', nombre: 'bailar', keywords: ['baile', 'fiesta'] },
    { emoji: '🕺', nombre: 'bailar hombre', keywords: ['baile', 'fiesta'] },
    { emoji: '🛀', nombre: 'banera', keywords: ['baño', 'higiene'] },
    { emoji: '🛌', nombre: 'cama', keywords: ['dormir', 'descansar'] },
    { emoji: '👨‍🏫', nombre: 'profesor', keywords: ['maestro', 'enseñar'] },
    { emoji: '👨‍⚕️', nombre: 'doctor', keywords: ['medico', 'salud'] },
    { emoji: '👨‍🔧', nombre: 'mecanico', keywords: ['reparar', 'herramienta'] },
    { emoji: '👨‍🍳', nombre: 'cocinero', keywords: ['cocina', 'chef'] },
    { emoji: '👨‍🌾', nombre: 'granjero', keywords: ['campo', 'agricultura'] },
    { emoji: '👨‍🚀', nombre: 'astronauta', keywords: ['espacio', 'nave'] },
  ],
  animales: [
    { emoji: '🐶', nombre: 'perro', keywords: ['perro', 'mascota'] },
    { emoji: '🐱', nombre: 'gato', keywords: ['gato', 'mascota'] },
    { emoji: '🐭', nombre: 'raton', keywords: ['raton', 'roedor'] },
    { emoji: '🐹', nombre: 'hamster', keywords: ['hamster', 'mascota'] },
    { emoji: '🐰', nombre: 'conejo', keywords: ['conejo', 'mascota'] },
    { emoji: '🦊', nombre: 'zorro', keywords: ['zorro', 'animal'] },
    { emoji: '🐻', nombre: 'oso', keywords: ['oso', 'animal'] },
    { emoji: '🐼', nombre: 'panda', keywords: ['panda', 'oso'] },
    { emoji: '🐨', nombre: 'koala', keywords: ['koala', 'animal'] },
    { emoji: '🐯', nombre: 'tigre', keywords: ['tigre', 'felino'] },
    { emoji: '🦁', nombre: 'leon', keywords: ['leon', 'felino'] },
    { emoji: '🐮', nombre: 'vaca', keywords: ['vaca', 'leche'] },
    { emoji: '🐷', nombre: 'cerdo', keywords: ['cerdo', 'chancho'] },
    { emoji: '🐸', nombre: 'rana', keywords: ['rana', 'anfibio'] },
    { emoji: '🐵', nombre: 'mono', keywords: ['mono', 'simio'] },
    { emoji: '🐔', nombre: 'pollo', keywords: ['pollo', 'gallina'] },
    { emoji: '🐧', nombre: 'pinguino', keywords: ['pinguino', 'ave'] },
    { emoji: '🐦', nombre: 'pajaro', keywords: ['pajaro', 'ave'] },
    { emoji: '🐤', nombre: 'pollito', keywords: ['pollito', 'bebe'] },
    { emoji: '🦆', nombre: 'pato', keywords: ['pato', 'ave'] },
    { emoji: '🦅', nombre: 'aguila', keywords: ['aguila', 'ave'] },
    { emoji: '🦉', nombre: 'buho', keywords: ['buho', 'ave', 'sabio'] },
    { emoji: '🦇', nombre: 'murcielago', keywords: ['murcielago', 'vampiro'] },
    { emoji: '🐺', nombre: 'lobo', keywords: ['lobo', 'animal'] },
    { emoji: '🐗', nombre: 'jabali', keywords: ['jabali', 'cerdo'] },
    { emoji: '🐴', nombre: 'caballo', keywords: ['caballo', 'yegua'] },
    { emoji: '🦄', nombre: 'unicornio', keywords: ['unicornio', 'fantasia'] },
    { emoji: '🐝', nombre: 'abeja', keywords: ['abeja', 'miel'] },
    { emoji: '🐛', nombre: 'oruga', keywords: ['oruga', 'insecto'] },
    { emoji: '🦋', nombre: 'mariposa', keywords: ['mariposa', 'insecto'] },
    { emoji: '🐌', nombre: 'caracol', keywords: ['caracol', 'lento'] },
    { emoji: '🐞', nombre: 'mariquita', keywords: ['catarina', 'insecto'] },
    { emoji: '🐜', nombre: 'hormiga', keywords: ['hormiga', 'insecto'] },
    { emoji: '🦟', nombre: 'mosquito', keywords: ['mosquito', 'picadura'] },
    { emoji: '🦗', nombre: 'grillo', keywords: ['grillo', 'insecto'] },
    { emoji: '🕷️', nombre: 'arana', keywords: ['araña', 'insecto'] },
    { emoji: '🦂', nombre: 'escorpion', keywords: ['escorpion', 'picadura'] },
    { emoji: '🐢', nombre: 'tortuga', keywords: ['tortuga', 'lento'] },
    { emoji: '🐍', nombre: 'serpiente', keywords: ['serpiente', 'culebra'] },
    { emoji: '🦎', nombre: 'lagarto', keywords: ['lagarto', 'reptil'] },
    { emoji: '🦖', nombre: 'tiranosaurio', keywords: ['dinosaurio', 'dino'] },
    { emoji: '🦕', nombre: 'dinosaurio', keywords: ['dinosaurio', 'dino'] },
    { emoji: '🐙', nombre: 'pulpo', keywords: ['pulpo', 'mar'] },
    { emoji: '🦑', nombre: 'calamar', keywords: ['calamar', 'mar'] },
    { emoji: '🦐', nombre: 'camaron', keywords: ['camaron', 'mar'] },
    { emoji: '🦞', nombre: 'langosta', keywords: ['langosta', 'mar'] },
    { emoji: '🐠', nombre: 'pez tropical', keywords: ['pez', 'mar'] },
    { emoji: '🐟', nombre: 'pez', keywords: ['pez', 'mar'] },
    { emoji: '🐡', nombre: 'pez globo', keywords: ['pez', 'mar'] },
    { emoji: '🐬', nombre: 'delfin', keywords: ['delfin', 'mar'] },
    { emoji: '🐳', nombre: 'ballena', keywords: ['ballena', 'mar'] },
    { emoji: '🐋', nombre: 'ballena grande', keywords: ['ballena', 'mar'] },
    { emoji: '🦈', nombre: 'tiburon', keywords: ['tiburon', 'mar'] },
    { emoji: '🐊', nombre: 'cocodrilo', keywords: ['cocodrilo', 'reptil'] },
    { emoji: '🐅', nombre: 'tigre', keywords: ['tigre', 'felino'] },
    { emoji: '🐆', nombre: 'leopardo', keywords: ['leopardo', 'felino'] },
    { emoji: '🦓', nombre: 'cebra', keywords: ['cebra', 'animal'] },
    { emoji: '🦍', nombre: 'gorila', keywords: ['gorila', 'simio'] },
    { emoji: '🦧', nombre: 'orangutan', keywords: ['orangutan', 'simio'] },
    { emoji: '🐘', nombre: 'elefante', keywords: ['elefante', 'animal'] },
    { emoji: '🦛', nombre: 'hipopotamo', keywords: ['hipopotamo', 'animal'] },
    { emoji: '🦏', nombre: 'rinoceronte', keywords: ['rinoceronte', 'animal'] },
    { emoji: '🐪', nombre: 'camello', keywords: ['camello', 'desierto'] },
    { emoji: '🐫', nombre: 'camello dos', keywords: ['camello', 'desierto'] },
    { emoji: '🦒', nombre: 'jirafa', keywords: ['jirafa', 'animal'] },
    { emoji: '🦘', nombre: 'canguro', keywords: ['canguro', 'australia'] },
    { emoji: '🦬', nombre: 'bisonte', keywords: ['bisonte', 'animal'] },
    { emoji: '🐃', nombre: 'bufalo', keywords: ['bufalo', 'animal'] },
    { emoji: '🐂', nombre: 'toro', keywords: ['toro', 'animal'] },
    { emoji: '🐄', nombre: 'vaca', keywords: ['vaca', 'leche'] },
    { emoji: '🐎', nombre: 'caballo', keywords: ['caballo', 'carrera'] },
    { emoji: '🐖', nombre: 'cerdo', keywords: ['cerdo', 'chancho'] },
    { emoji: '🐏', nombre: 'carnero', keywords: ['carnero', 'oveja'] },
    { emoji: '🐑', nombre: 'oveja', keywords: ['oveja', 'lana'] },
    { emoji: '🐐', nombre: 'cabra', keywords: ['cabra', 'animal'] },
    { emoji: '🦌', nombre: 'venado', keywords: ['venado', 'ciervo'] },
    { emoji: '🐕', nombre: 'perro', keywords: ['perro', 'mascota'] },
    { emoji: '🐩', nombre: 'poodle', keywords: ['perro', 'mascota'] },
    { emoji: '🦮', nombre: 'perro guia', keywords: ['perro', 'guia'] },
    { emoji: '🐕‍🦺', nombre: 'perro servicio', keywords: ['perro', 'apoyo'] },
    { emoji: '🐈', nombre: 'gato', keywords: ['gato', 'mascota'] },
    { emoji: '🐈‍⬛', nombre: 'gato negro', keywords: ['gato', 'negro'] },
    { emoji: '🐓', nombre: 'gallo', keywords: ['gallo', 'granja'] },
    { emoji: '🦃', nombre: 'pavo', keywords: ['pavo', 'gracias'] },
    { emoji: '🦤', nombre: 'dodo', keywords: ['pajaro', 'extinto'] },
    { emoji: '🦚', nombre: 'pavo real', keywords: ['pavo', 'plumas'] },
    { emoji: '🦜', nombre: 'loro', keywords: ['loro', 'papagayo'] },
    { emoji: '🦢', nombre: 'cisne', keywords: ['cisne', 'ave'] },
    { emoji: '🪶', nombre: 'pluma', keywords: ['pluma', 'ave'] },
    { emoji: '🦩', nombre: 'flamenco', keywords: ['flamenco', 'ave'] },
    { emoji: '🕊️', nombre: 'paloma', keywords: ['paloma', 'paz'] },
    { emoji: '🐇', nombre: 'conejo', keywords: ['conejo', 'mascota'] },
    { emoji: '🦝', nombre: 'mapache', keywords: ['mapache', 'animal'] },
    { emoji: '🦨', nombre: 'zorrillo', keywords: ['zorrillo', 'mofeta'] },
    { emoji: '🦡', nombre: 'tejon', keywords: ['tejon', 'animal'] },
    { emoji: '🦫', nombre: 'castor', keywords: ['castor', 'animal'] },
    { emoji: '🦦', nombre: 'nutria', keywords: ['nutria', 'animal'] },
    { emoji: '🦥', nombre: 'perezoso', keywords: ['perezoso', 'lento'] },
    { emoji: '🐾', nombre: 'huellas', keywords: ['patas', 'animal'] },
    { emoji: '🦔', nombre: 'erizo', keywords: ['erizo', 'animal'] },
    { emoji: '🐿️', nombre: 'ardilla', keywords: ['ardilla', 'roedor'] },
    { emoji: '🦇', nombre: 'murcielago', keywords: ['murcielago', 'vampiro'] },
    { emoji: '🌵', nombre: 'cactus', keywords: ['cactus', 'desierto'] },
    { emoji: '🎄', nombre: 'arbol navidad', keywords: ['navidad', 'pino'] },
    { emoji: '🌲', nombre: 'pino', keywords: ['arbol', 'bosque'] },
    { emoji: '🌳', nombre: 'arbol', keywords: ['arbol', 'bosque'] },
    { emoji: '🌴', nombre: 'palmera', keywords: ['palmera', 'tropical'] },
    { emoji: '🌵', nombre: 'cactus', keywords: ['cactus'] },
    { emoji: '🌾', nombre: 'espiga', keywords: ['trigo', 'campo'] },
    { emoji: '🌿', nombre: 'hierba', keywords: ['planta', 'verde'] },
    { emoji: '🍀', nombre: 'trebol', keywords: ['suerte', 'trebol'] },
    { emoji: '🍁', nombre: 'hoja arce', keywords: ['otono', 'canada'] },
    { emoji: '🍂', nombre: 'hoja caida', keywords: ['otono', 'hoja'] },
    { emoji: '🍃', nombre: 'hoja viento', keywords: ['hoja', 'viento'] },
    { emoji: '🌺', nombre: 'hibisco', keywords: ['flor', 'tropical'] },
    { emoji: '🌸', nombre: 'cerezo', keywords: ['flor', 'primavera'] },
    { emoji: '🌼', nombre: 'margarita', keywords: ['flor', 'amarillo'] },
    { emoji: '🌻', nombre: 'girasol', keywords: ['flor', 'sol'] },
    { emoji: '🌹', nombre: 'rosa', keywords: ['flor', 'amor'] },
    { emoji: '🌷', nombre: 'tulipan', keywords: ['flor', 'primavera'] },
    { emoji: '🌱', nombre: 'brote', keywords: ['planta', 'crecer'] },
    { emoji: '🪴', nombre: 'maceta', keywords: ['planta', 'mascota'] },
    { emoji: '🍄', nombre: 'hongo', keywords: ['seta', 'champiñon'] },
    { emoji: '🌰', nombre: 'castaña', keywords: ['fruto', 'otono'] },
    { emoji: '🦀', nombre: 'cangrejo', keywords: ['cangrejo', 'mar'] },
    { emoji: '🦪', nombre: 'ostra', keywords: ['ostra', 'mar'] },
  ],
  comida: [
    { emoji: '🍏', nombre: 'manzana verde', keywords: ['manzana', 'fruta'] },
    { emoji: '🍎', nombre: 'manzana roja', keywords: ['manzana', 'fruta'] },
    { emoji: '🍐', nombre: 'pera', keywords: ['pera', 'fruta'] },
    { emoji: '🍊', nombre: 'naranja', keywords: ['naranja', 'citrico'] },
    { emoji: '🍋', nombre: 'limon', keywords: ['limon', 'citrico'] },
    { emoji: '🍌', nombre: 'platano', keywords: ['platano', 'banana'] },
    { emoji: '🍉', nombre: 'sandia', keywords: ['sandia', 'fruta'] },
    { emoji: '🍇', nombre: 'uva', keywords: ['uva', 'fruta'] },
    { emoji: '🍓', nombre: 'fresa', keywords: ['fresa', 'frutilla'] },
    { emoji: '🫐', nombre: 'arandanos', keywords: ['arandano', 'fruta'] },
    { emoji: '🍈', nombre: 'melon', keywords: ['melon', 'fruta'] },
    { emoji: '🍒', nombre: 'cereza', keywords: ['cereza', 'fruta'] },
    { emoji: '🍑', nombre: 'durazno', keywords: ['durazno', 'melocoton'] },
    { emoji: '🥭', nombre: 'mango', keywords: ['mango', 'fruta'] },
    { emoji: '🍍', nombre: 'pina', keywords: ['piña', 'fruta'] },
    { emoji: '🥝', nombre: 'kiwi', keywords: ['kiwi', 'fruta'] },
    { emoji: '🍅', nombre: 'tomate', keywords: ['tomate', 'jitomate'] },
    { emoji: '🥑', nombre: 'palta', keywords: ['palta', 'aguacate'] },
    { emoji: '🥦', nombre: 'brocoli', keywords: ['brocoli', 'verdura'] },
    { emoji: '🥬', nombre: 'lechuga', keywords: ['lechuga', 'verdura'] },
    { emoji: '🥒', nombre: 'pepino', keywords: ['pepino', 'verdura'] },
    { emoji: '🌽', nombre: 'maiz', keywords: ['maiz', 'choclo'] },
    { emoji: '🥕', nombre: 'zanahoria', keywords: ['zanahoria', 'verdura'] },
    { emoji: '🧄', nombre: 'ajo', keywords: ['ajo', 'condimento'] },
    { emoji: '🧅', nombre: 'cebolla', keywords: ['cebolla', 'condimento'] },
    { emoji: '🥔', nombre: 'papa', keywords: ['papa', 'patata'] },
    { emoji: '🍠', nombre: 'camote', keywords: ['camote', 'batata'] },
    { emoji: '🥐', nombre: 'croissant', keywords: ['pan', 'masa'] },
    { emoji: '🥖', nombre: 'baguette', keywords: ['pan', 'frances'] },
    { emoji: '🍞', nombre: 'pan', keywords: ['pan', 'tostada'] },
    { emoji: '🥯', nombre: 'bagel', keywords: ['pan', 'rosquilla'] },
    { emoji: '🧀', nombre: 'queso', keywords: ['queso', 'lacteo'] },
    { emoji: '🥚', nombre: 'huevo', keywords: ['huevo', 'ovo'] },
    { emoji: '🍳', nombre: 'sarten', keywords: ['huevo', 'cocinar'] },
    { emoji: '🥞', nombre: 'panqueques', keywords: ['panqueque', 'hotcake'] },
    { emoji: '🧇', nombre: 'waffle', keywords: ['waffle', 'masa'] },
    { emoji: '🥓', nombre: 'tocino', keywords: ['tocino', 'bacon'] },
    { emoji: '🥩', nombre: 'carne', keywords: ['carne', 'bistec'] },
    { emoji: '🍗', nombre: 'pierna pollo', keywords: ['pollo', 'carne'] },
    { emoji: '🍖', nombre: 'hueso', keywords: ['carne', 'hueso'] },
    { emoji: '🌭', nombre: 'perro caliente', keywords: ['hotdog', 'completo'] },
    { emoji: '🍔', nombre: 'hamburguesa', keywords: ['hamburguesa', 'comida'] },
    { emoji: '🍟', nombre: 'papas fritas', keywords: ['papas', 'fritas'] },
    { emoji: '🍕', nombre: 'pizza', keywords: ['pizza', 'comida'] },
    { emoji: '🥪', nombre: 'sandwich', keywords: ['sandwich', 'comida'] },
    { emoji: '🥙', nombre: 'kebab', keywords: ['kebab', 'comida'] },
    { emoji: '🌮', nombre: 'taco', keywords: ['taco', 'comida'] },
    { emoji: '🌯', nombre: 'burrito', keywords: ['burrito', 'comida'] },
    { emoji: '🥗', nombre: 'ensalada', keywords: ['ensalada', 'verdura'] },
    { emoji: '🥘', nombre: 'paella', keywords: ['paella', 'comida'] },
    { emoji: '🍝', nombre: 'pasta', keywords: ['pasta', 'espagueti'] },
    { emoji: '🍜', nombre: 'fideos', keywords: ['fideos', 'sopa'] },
    { emoji: '🍲', nombre: 'olla', keywords: ['sopa', 'guiso'] },
    { emoji: '🍛', nombre: 'curry', keywords: ['curry', 'comida'] },
    { emoji: '🍣', nombre: 'sushi', keywords: ['sushi', 'comida'] },
    { emoji: '🍤', nombre: 'camaron frito', keywords: ['camaron', 'tempura'] },
    { emoji: '🍥', nombre: 'naruto', keywords: ['pastel', 'pescado'] },
    { emoji: '🥮', nombre: 'pastel luna', keywords: ['pastel', 'luna'] },
    { emoji: '🍡', nombre: 'dango', keywords: ['dulce', 'japones'] },
    { emoji: '🥟', nombre: 'empanada', keywords: ['empanada', 'gyoza'] },
    { emoji: '🦪', nombre: 'ostra', keywords: ['ostra', 'mar'] },
    { emoji: '🍦', nombre: 'helado', keywords: ['helado', 'nieve'] },
    { emoji: '🍧', nombre: 'raspado', keywords: ['hielo', 'dulce'] },
    { emoji: '🍨', nombre: 'helado taza', keywords: ['helado', 'postre'] },
    { emoji: '🍩', nombre: 'dona', keywords: ['dona', 'rosquilla'] },
    { emoji: '🍪', nombre: 'galleta', keywords: ['galleta', 'dulce'] },
    { emoji: '🎂', nombre: 'pastel', keywords: ['pastel', 'cumpleaños'] },
    { emoji: '🍰', nombre: 'torta', keywords: ['torta', 'queque'] },
    { emoji: '🧁', nombre: 'cupcake', keywords: ['cupcake', 'dulce'] },
    { emoji: '🥧', nombre: 'pay', keywords: ['pay', 'tarta'] },
    { emoji: '🍫', nombre: 'chocolate', keywords: ['chocolate', 'dulce'] },
    { emoji: '🍬', nombre: 'caramelo', keywords: ['caramelo', 'dulce'] },
    { emoji: '🍭', nombre: 'chupete', keywords: ['chupete', 'dulce'] },
    { emoji: '🍮', nombre: 'flan', keywords: ['flan', 'postre'] },
    { emoji: '🍯', nombre: 'miel', keywords: ['miel', 'abeja'] },
    { emoji: '🍼', nombre: 'biberon', keywords: ['bebe', 'leche'] },
    { emoji: '🥛', nombre: 'leche', keywords: ['leche', 'lacteo'] },
    { emoji: '☕', nombre: 'cafe', keywords: ['cafe', 'caliente'] },
    { emoji: '🫖', nombre: 'tetera', keywords: ['te', 'infusion'] },
    { emoji: '🍵', nombre: 'te', keywords: ['te', 'infusion'] },
    { emoji: '🧃', nombre: 'jugo', keywords: ['jugo', 'caja'] },
    { emoji: '🥤', nombre: 'vaso', keywords: ['vaso', 'bebida'] },
    { emoji: '🧊', nombre: 'hielo', keywords: ['hielo', 'cubito'] },
    { emoji: '🍶', nombre: 'sake', keywords: ['sake', 'japones'] },
    { emoji: '🍺', nombre: 'cerveza', keywords: ['cerveza'] },
    { emoji: '🍻', nombre: 'cervezas', keywords: ['cerveza', 'brindis'] },
    { emoji: '🥂', nombre: 'brindis', keywords: ['brindis', 'copas'] },
    { emoji: '🥃', nombre: 'whisky', keywords: ['whisky', 'traguito'] },
    { emoji: '🫗', nombre: 'servir', keywords: ['servir', 'liquido'] },
    { emoji: '🥄', nombre: 'cuchara', keywords: ['cuchara', 'cubierto'] },
    { emoji: '🍴', nombre: 'tenedor cuchillo', keywords: ['cubiertos', 'comer'] },
    { emoji: '🥢', nombre: 'palillos', keywords: ['palillos', 'comer'] },
    { emoji: '🔪', nombre: 'cuchillo', keywords: ['cuchillo', 'cortar'] },
    { emoji: '🏺', nombre: 'anfora', keywords: ['jarron', 'vasija'] },
  ],
  actividades: [
    { emoji: '⚽', nombre: 'futbol', keywords: ['futbol', 'deporte'] },
    { emoji: '🏀', nombre: 'basquet', keywords: ['basquetbol', 'deporte'] },
    { emoji: '🏈', nombre: 'futbol americano', keywords: ['futbol', 'americano'] },
    { emoji: '⚾', nombre: 'beisbol', keywords: ['beisbol', 'deporte'] },
    { emoji: '🥎', nombre: 'softbol', keywords: ['softbol', 'deporte'] },
    { emoji: '🎾', nombre: 'tenis', keywords: ['tenis', 'deporte'] },
    { emoji: '🏐', nombre: 'voleibol', keywords: ['voley', 'deporte'] },
    { emoji: '🏉', nombre: 'rugby', keywords: ['rugby', 'deporte'] },
    { emoji: '🥏', nombre: 'disco', keywords: ['disco', 'frisbee'] },
    { emoji: '🎱', nombre: 'billar', keywords: ['billar', 'bola ocho'] },
    { emoji: '🪀', nombre: 'yo-yo', keywords: ['yoyo', 'juguete'] },
    { emoji: '🏓', nombre: 'ping pong', keywords: ['tenis mesa', 'deporte'] },
    { emoji: '🏸', nombre: 'badminton', keywords: ['badminton', 'deporte'] },
    { emoji: '🥊', nombre: 'boxeo', keywords: ['boxeo', 'guante'] },
    { emoji: '🥋', nombre: 'karate', keywords: ['karate', 'arte marcial'] },
    { emoji: '🎯', nombre: 'diana', keywords: ['blanco', 'punteria'] },
    { emoji: '⛳', nombre: 'golf', keywords: ['golf', 'hoyo'] },
    { emoji: '🎣', nombre: 'pescar', keywords: ['pesca', 'caña'] },
    { emoji: '🤿', nombre: 'buceo', keywords: ['bucear', 'mar'] },
    { emoji: '🎿', nombre: 'esqui', keywords: ['esqui', 'nieve'] },
    { emoji: '🛷', nombre: 'trineo', keywords: ['trineo', 'nieve'] },
    { emoji: '🥌', nombre: 'curling', keywords: ['curling', 'piedra'] },
    { emoji: '🎮', nombre: 'videojuego', keywords: ['juego', 'consola'] },
    { emoji: '🕹️', nombre: 'joystick', keywords: ['mando', 'juego'] },
    { emoji: '🎲', nombre: 'dado', keywords: ['dado', 'azar'] },
    { emoji: '♟️', nombre: 'ajedrez', keywords: ['ajedrez', 'tablero'] },
    { emoji: '🃏', nombre: 'comodin', keywords: ['carta', 'juego'] },
    { emoji: '🀄', nombre: 'mahjong', keywords: ['mahjong', 'ficha'] },
    { emoji: '🎴', nombre: 'carta', keywords: ['carta', 'juego'] },
    { emoji: '🎭', nombre: 'teatro', keywords: ['teatro', 'actuar'] },
    { emoji: '🎨', nombre: 'arte', keywords: ['pintura', 'dibujar'] },
    { emoji: '✏️', nombre: 'lapiz', keywords: ['lapiz', 'escribir'] },
    { emoji: '🖊️', nombre: 'boligrafo', keywords: ['boligrafo', 'lapicero'] },
    { emoji: '📚', nombre: 'libros', keywords: ['libro', 'estudiar'] },
    { emoji: '📖', nombre: 'libro abierto', keywords: ['libro', 'leer'] },
    { emoji: '📕', nombre: 'libro rojo', keywords: ['libro', 'leer'] },
    { emoji: '📗', nombre: 'libro verde', keywords: ['libro', 'leer'] },
    { emoji: '📘', nombre: 'libro azul', keywords: ['libro', 'leer'] },
    { emoji: '📙', nombre: 'libro naranja', keywords: ['libro', 'leer'] },
    { emoji: '📒', nombre: 'libreta', keywords: ['libreta', 'cuaderno'] },
    { emoji: '📃', nombre: 'pagina', keywords: ['pagina', 'documento'] },
    { emoji: '📜', nombre: 'pergamino', keywords: ['pergamino', 'antiguo'] },
    { emoji: '📄', nombre: 'documento', keywords: ['documento', 'archivo'] },
    { emoji: '📰', nombre: 'periodico', keywords: ['periodico', 'noticias'] },
    { emoji: '🎵', nombre: 'nota musical', keywords: ['musica', 'nota'] },
    { emoji: '🎶', nombre: 'notas', keywords: ['musica', 'cancion'] },
    { emoji: '🎼', nombre: 'partitura', keywords: ['musica', 'pentagrama'] },
    { emoji: '🎤', nombre: 'microfono', keywords: ['microfono', 'cantar'] },
    { emoji: '🎧', nombre: 'audifonos', keywords: ['audifonos', 'musica'] },
    { emoji: '📻', nombre: 'radio', keywords: ['radio', 'musica'] },
    { emoji: '🎷', nombre: 'saxofon', keywords: ['saxofon', 'instrumento'] },
    { emoji: '🎸', nombre: 'guitarra', keywords: ['guitarra', 'instrumento'] },
    { emoji: '🎹', nombre: 'piano', keywords: ['piano', 'instrumento'] },
    { emoji: '🎺', nombre: 'trompeta', keywords: ['trompeta', 'instrumento'] },
    { emoji: '🎻', nombre: 'violin', keywords: ['violin', 'instrumento'] },
    { emoji: '🪕', nombre: 'banjo', keywords: ['banjo', 'instrumento'] },
    { emoji: '🥁', nombre: 'tambor', keywords: ['tambor', 'bateria'] },
    { emoji: '🔔', nombre: 'campana', keywords: ['campana', 'sonido'] },
    { emoji: '🎫', nombre: 'ticket', keywords: ['boleto', 'entrada'] },
    { emoji: '🏆', nombre: 'trofeo', keywords: ['trofeo', 'victoria'] },
    { emoji: '🥇', nombre: 'oro', keywords: ['medalla', 'oro'] },
    { emoji: '🥈', nombre: 'plata', keywords: ['medalla', 'plata'] },
    { emoji: '🥉', nombre: 'bronce', keywords: ['medalla', 'bronce'] },
  ],
  casa: [
    { emoji: '🏠', nombre: 'casa', keywords: ['hogar', 'casa'] },
    { emoji: '🏡', nombre: 'casa jardin', keywords: ['hogar', 'casa'] },
    { emoji: '🏢', nombre: 'edificio', keywords: ['oficina', 'trabajo'] },
    { emoji: '🏣', nombre: 'correo', keywords: ['correo', 'carta'] },
    { emoji: '🏥', nombre: 'hospital', keywords: ['hospital', 'salud'] },
    { emoji: '🏪', nombre: 'tienda', keywords: ['tienda', 'compras'] },
    { emoji: '🏫', nombre: 'escuela', keywords: ['colegio', 'estudiar'] },
    { emoji: '🏩', nombre: 'hotel amor', keywords: ['hotel'] },
    { emoji: '🏬', nombre: 'centro comercial', keywords: ['compras', 'tiendas'] },
    { emoji: '🏰', nombre: 'castillo', keywords: ['castillo', 'palacio'] },
    { emoji: '🏯', nombre: 'castillo japones', keywords: ['castillo', 'japon'] },
    { emoji: '💒', nombre: 'iglesia', keywords: ['iglesia', 'boda'] },
    { emoji: '🗼', nombre: 'torre eiffel', keywords: ['torre', 'paris'] },
    { emoji: '🗽', nombre: 'estatua libertad', keywords: ['estatua', 'ny'] },
    { emoji: '⛪', nombre: 'iglesia', keywords: ['iglesia'] },
    { emoji: '🛋️', nombre: 'sillon', keywords: ['sillon', 'mueble'] },
    { emoji: '🛏️', nombre: 'cama', keywords: ['cama', 'dormitorio'] },
    { emoji: '🪑', nombre: 'silla', keywords: ['silla', 'asiento'] },
    { emoji: '🚪', nombre: 'puerta', keywords: ['puerta', 'entrada'] },
    { emoji: '🪟', nombre: 'ventana', keywords: ['ventana', 'abrir'] },
    { emoji: '🪞', nombre: 'espejo', keywords: ['espejo', 'reflejo'] },
    { emoji: '💡', nombre: 'bombilla', keywords: ['luz', 'idea'] },
    { emoji: '🔦', nombre: 'linterna', keywords: ['luz', 'mano'] },
    { emoji: '🧯', nombre: 'extintor', keywords: ['fuego', 'seguridad'] },
    { emoji: '🪣', nombre: 'balde', keywords: ['balde', 'cubo'] },
    { emoji: '🧹', nombre: 'escoba', keywords: ['barrer', 'limpiar'] },
    { emoji: '🧺', nombre: 'canasta', keywords: ['cesta', 'ropa'] },
    { emoji: '🧻', nombre: 'papel', keywords: ['papel', 'higienico'] },
    { emoji: '🚿', nombre: 'ducha', keywords: ['ducha', 'bañarse'] },
    { emoji: '🛁', nombre: 'banera', keywords: ['bañera', 'baño'] },
    { emoji: '🪥', nombre: 'cepillo dientes', keywords: ['dientes', 'higiene'] },
    { emoji: '🧴', nombre: 'lotion', keywords: ['crema', 'lotion'] },
    { emoji: '🧽', nombre: 'esponja', keywords: ['esponja', 'limpiar'] },
    { emoji: '🧼', nombre: 'jabon', keywords: ['jabon', 'lavar'] },
    { emoji: '🪒', nombre: 'rastrillo', keywords: ['afeitar', 'rasurar'] },
    { emoji: '🪮', nombre: 'peine', keywords: ['peine', 'peinar'] },
    { emoji: '👕', nombre: 'camiseta', keywords: ['polera', 'ropa'] },
    { emoji: '👖', nombre: 'pantalon', keywords: ['pantalon', 'jeans'] },
    { emoji: '🧥', nombre: 'abrigo', keywords: ['chaqueta', 'abrigo'] },
    { emoji: '👗', nombre: 'vestido', keywords: ['vestido', 'falda'] },
    { emoji: '👘', nombre: 'kimono', keywords: ['kimono', 'japones'] },
    { emoji: '👙', nombre: 'bikini', keywords: ['bikini', 'playa'] },
    { emoji: '👚', nombre: 'ropa mujer', keywords: ['ropa', 'blusa'] },
    { emoji: '👔', nombre: 'corbata', keywords: ['corbata', 'formal'] },
    { emoji: '👞', nombre: 'zapato', keywords: ['zapato', 'calzado'] },
    { emoji: '👟', nombre: 'zapatilla', keywords: ['zapatilla', 'deporte'] },
    { emoji: '👠', nombre: 'taco', keywords: ['taco', 'mujer'] },
    { emoji: '👑', nombre: 'corona', keywords: ['corona', 'rey'] },
    { emoji: '🎒', nombre: 'mochila', keywords: ['mochila', 'colegio'] },
    { emoji: '👝', nombre: 'bolso', keywords: ['bolso', 'cartera'] },
    { emoji: '👛', nombre: 'monedero', keywords: ['monedero', 'cartera'] },
    { emoji: '👜', nombre: 'cartera', keywords: ['cartera', 'bolsa'] },
    { emoji: '💼', nombre: 'maletin', keywords: ['maletin', 'trabajo'] },
    { emoji: '🕶️', nombre: 'lentes', keywords: ['lentes', 'sol'] },
    { emoji: '⌚', nombre: 'reloj', keywords: ['reloj', 'hora'] },
    { emoji: '📱', nombre: 'celular', keywords: ['telefono', 'movil'] },
    { emoji: '💻', nombre: 'laptop', keywords: ['computador', 'notebook'] },
    { emoji: '🖥️', nombre: 'monitor', keywords: ['computador', 'pantalla'] },
    { emoji: '🖨️', nombre: 'impresora', keywords: ['impresora', 'imprimir'] },
    { emoji: '📷', nombre: 'camara', keywords: ['camara', 'foto'] },
    { emoji: '📸', nombre: 'camara flash', keywords: ['camara', 'foto'] },
    { emoji: '🎥', nombre: 'camara video', keywords: ['video', 'filmacion'] },
    { emoji: '📺', nombre: 'televisor', keywords: ['tv', 'television'] },
    { emoji: '🔌', nombre: 'enchufe', keywords: ['enchufe', 'electricidad'] },
    { emoji: '🔋', nombre: 'bateria', keywords: ['pila', 'carga'] },
    { emoji: '🪴', nombre: 'planta', keywords: ['planta', 'maceta'] },
    { emoji: '🧸', nombre: 'peluche', keywords: ['oso', 'juguete'] },
    { emoji: '🖼️', nombre: 'cuadro', keywords: ['pintura', 'marco'] },
    { emoji: '🧲', nombre: 'iman', keywords: ['iman', 'magnetico'] },
    { emoji: '🔑', nombre: 'llave', keywords: ['llave', 'abrir'] },
    { emoji: '🗝️', nombre: 'llave vieja', keywords: ['llave', 'antigua'] },
    { emoji: '🔨', nombre: 'martillo', keywords: ['martillo', 'herramienta'] },
    { emoji: '🪓', nombre: 'hacha', keywords: ['hacha', 'cortar'] },
    { emoji: '🪛', nombre: 'destornillador', keywords: ['destornillador', 'herramienta'] },
    { emoji: '🔧', nombre: 'llave inglesa', keywords: ['herramienta', 'reparar'] },
    { emoji: '🔩', nombre: 'tuerca', keywords: ['tornillo', 'tuerca'] },
    { emoji: '⚙️', nombre: 'engranaje', keywords: ['rueda', 'mecanismo'] },
    { emoji: '🧰', nombre: 'caja herramientas', keywords: ['herramientas', 'reparar'] },
    { emoji: '🧪', nombre: 'tubo ensayo', keywords: ['experimento', 'laboratorio'] },
    { emoji: '🔬', nombre: 'microscopio', keywords: ['microscopio', 'ciencia'] },
    { emoji: '🔭', nombre: 'telescopio', keywords: ['telescopio', 'estrellas'] },
    { emoji: '📡', nombre: 'antena', keywords: ['satelite', 'señal'] },
    { emoji: '💉', nombre: 'jeringa', keywords: ['jeringa', 'inyeccion'] },
    { emoji: '🩹', nombre: 'curita', keywords: ['curita', 'herida'] },
    { emoji: '🩺', nombre: 'estetoscopio', keywords: ['medico', 'salud'] },
  ],
  viajes: [
    { emoji: '🚗', nombre: 'auto', keywords: ['carro', 'coche'] },
    { emoji: '🚙', nombre: 'auto familiar', keywords: ['suv', 'coche'] },
    { emoji: '🚕', nombre: 'taxi', keywords: ['taxi', 'auto'] },
    { emoji: '🚓', nombre: 'policia', keywords: ['patrulla', 'policia'] },
    { emoji: '🚑', nombre: 'ambulancia', keywords: ['ambulancia', 'medico'] },
    { emoji: '🚒', nombre: 'bomberos', keywords: ['bomberos', 'fuego'] },
    { emoji: '🚐', nombre: 'van', keywords: ['van', 'micro'] },
    { emoji: '🚌', nombre: 'bus', keywords: ['bus', 'micro'] },
    { emoji: '🚎', nombre: 'trolebus', keywords: ['bus', 'micro'] },
    { emoji: '🏎️', nombre: 'auto carrera', keywords: ['f1', 'deporte'] },
    { emoji: '🚓', nombre: 'policia', keywords: ['patrulla'] },
    { emoji: '🚜', nombre: 'tractor', keywords: ['tractor', 'campo'] },
    { emoji: '🛴', nombre: 'scooter', keywords: ['patineta', 'electrico'] },
    { emoji: '🚲', nombre: 'bicicleta', keywords: ['bici', 'ciclo'] },
    { emoji: '🛵', nombre: 'moto', keywords: ['moto', 'scooter'] },
    { emoji: '🏍️', nombre: 'moto', keywords: ['moto', 'motocicleta'] },
    { emoji: '🚂', nombre: 'tren', keywords: ['tren', 'ferrocarril'] },
    { emoji: '🚀', nombre: 'cohete', keywords: ['nave', 'espacio'] },
    { emoji: '🛸', nombre: 'ovni', keywords: ['ufo', 'extraterrestre'] },
    { emoji: '✈️', nombre: 'avion', keywords: ['avion', 'volar'] },
    { emoji: '🛩️', nombre: 'avioneta', keywords: ['avion', 'volar'] },
    { emoji: '🛫', nombre: 'despegue', keywords: ['avion', 'volar'] },
    { emoji: '🛬', nombre: 'aterrizaje', keywords: ['avion', 'llegada'] },
    { emoji: '⛵', nombre: 'velero', keywords: ['barco', 'navegar'] },
    { emoji: '🛥️', nombre: 'lancha', keywords: ['barco', 'navegar'] },
    { emoji: '🚢', nombre: 'barco', keywords: ['buque', 'nave'] },
    { emoji: '🛶', nombre: 'canoa', keywords: ['canoa', 'remo'] },
    { emoji: '🛟', nombre: 'salvavidas', keywords: ['flotador', 'salvar'] },
    { emoji: '🚏', nombre: 'parada', keywords: ['bus', 'paradero'] },
    { emoji: '⛽', nombre: 'gasolinera', keywords: ['gasolina', 'combustible'] },
    { emoji: '🛤️', nombre: 'via tren', keywords: ['tren', 'riel'] },
    { emoji: '🗺️', nombre: 'mapa', keywords: ['mapa', 'viaje'] },
    { emoji: '🧭', nombre: 'brujula', keywords: ['brujula', 'norte'] },
    { emoji: '⛰️', nombre: 'montaña', keywords: ['montaña', 'cerro'] },
    { emoji: '🏔️', nombre: 'montaña nieve', keywords: ['montaña', 'nieve'] },
    { emoji: '🌋', nombre: 'volcan', keywords: ['volcan', 'lava'] },
    { emoji: '🏖️', nombre: 'playa', keywords: ['playa', 'arena'] },
    { emoji: '🏝️', nombre: 'isla', keywords: ['isla', 'playa'] },
    { emoji: '🏜️', nombre: 'desierto', keywords: ['desierto', 'arena'] },
    { emoji: '🌅', nombre: 'amanecer', keywords: ['sol', 'mañana'] },
    { emoji: '🌄', nombre: 'amanecer montaña', keywords: ['sol', 'mañana'] },
    { emoji: '🌇', nombre: 'atardecer', keywords: ['sol', 'tarde'] },
    { emoji: '🌌', nombre: 'via lactea', keywords: ['estrellas', 'galaxia'] },
    { emoji: '🏙️', nombre: 'ciudad', keywords: ['ciudad', 'edificios'] },
    { emoji: '🌉', nombre: 'puente noche', keywords: ['puente', 'ciudad'] },
    { emoji: '🎡', nombre: 'rueda', keywords: ['feria', 'parque'] },
    { emoji: '🎢', nombre: 'montaña rusa', keywords: ['parque', 'entretencion'] },
    { emoji: '🎠', nombre: 'caballo', keywords: ['carrusel', 'feria'] },
    { emoji: '🎪', nombre: 'circo', keywords: ['circo', 'carpa'] },
    { emoji: '🎭', nombre: 'teatro', keywords: ['teatro', 'obra'] },
  ],
  simbolos: [
    { emoji: '❤️', nombre: 'corazon rojo', keywords: ['amor', 'corazon'] },
    { emoji: '🧡', nombre: 'corazon naranja', keywords: ['amor'] },
    { emoji: '💛', nombre: 'corazon amarillo', keywords: ['amor'] },
    { emoji: '💚', nombre: 'corazon verde', keywords: ['amor'] },
    { emoji: '💙', nombre: 'corazon azul', keywords: ['amor'] },
    { emoji: '💜', nombre: 'corazon morado', keywords: ['amor'] },
    { emoji: '🖤', nombre: 'corazon negro', keywords: ['amor'] },
    { emoji: '🤍', nombre: 'corazon blanco', keywords: ['amor'] },
    { emoji: '🤎', nombre: 'corazon cafe', keywords: ['amor'] },
    { emoji: '💔', nombre: 'corazon roto', keywords: ['triste', 'romper'] },
    { emoji: '❣️', nombre: 'exclamacion corazon', keywords: ['amor'] },
    { emoji: '💕', nombre: 'corazones', keywords: ['amor', 'pareja'] },
    { emoji: '💞', nombre: 'corazones girando', keywords: ['amor'] },
    { emoji: '💓', nombre: 'corazon latiendo', keywords: ['amor'] },
    { emoji: '💗', nombre: 'corazon creciendo', keywords: ['amor'] },
    { emoji: '💖', nombre: 'corazon brillante', keywords: ['amor'] },
    { emoji: '💘', nombre: 'flecha corazon', keywords: ['amor', 'cupido'] },
    { emoji: '💝', nombre: 'corazon cinta', keywords: ['amor', 'regalo'] },
    { emoji: '⭐', nombre: 'estrella', keywords: ['estrella', 'favorito'] },
    { emoji: '🌟', nombre: 'estrella brillante', keywords: ['estrella', 'brillo'] },
    { emoji: '✨', nombre: 'brillo', keywords: ['destello', 'magia'] },
    { emoji: '💫', nombre: 'mareado', keywords: ['destello', 'estrella'] },
    { emoji: '🔥', nombre: 'fuego', keywords: ['caliente', 'fuego'] },
    { emoji: '💥', nombre: 'explosion', keywords: ['choque', 'explotar'] },
    { emoji: '💢', nombre: 'enojo', keywords: ['enojo', 'rabia'] },
    { emoji: '💦', nombre: 'sudor', keywords: ['agua', 'gotas'] },
    { emoji: '💤', nombre: 'sueno', keywords: ['dormir', 'zzz'] },
    { emoji: '💨', nombre: 'viento', keywords: ['correr', 'rapido'] },
    { emoji: '🕳️', nombre: 'hoyo', keywords: ['agujero', 'hueco'] },
    { emoji: '💬', nombre: 'burbuja', keywords: ['dialogo', 'mensaje'] },
    { emoji: '🗯️', nombre: 'burbuja rabia', keywords: ['dialogo', 'enojo'] },
    { emoji: '👁️‍🗨️', nombre: 'ojo dialogo', keywords: ['mirar'] },
    { emoji: '🔴', nombre: 'circulo rojo', keywords: ['rojo', 'circulo'] },
    { emoji: '🟠', nombre: 'circulo naranja', keywords: ['naranja', 'circulo'] },
    { emoji: '🟡', nombre: 'circulo amarillo', keywords: ['amarillo', 'circulo'] },
    { emoji: '🟢', nombre: 'circulo verde', keywords: ['verde', 'circulo'] },
    { emoji: '🔵', nombre: 'circulo azul', keywords: ['azul', 'circulo'] },
    { emoji: '🟣', nombre: 'circulo morado', keywords: ['morado', 'circulo'] },
    { emoji: '⚫', nombre: 'circulo negro', keywords: ['negro', 'circulo'] },
    { emoji: '⚪', nombre: 'circulo blanco', keywords: ['blanco', 'circulo'] },
    { emoji: '🟤', nombre: 'circulo cafe', keywords: ['cafe', 'circulo'] },
    { emoji: '🔲', nombre: 'boton negro', keywords: ['cuadrado', 'boton'] },
    { emoji: '🔳', nombre: 'boton blanco', keywords: ['cuadrado', 'boton'] },
    { emoji: '✅', nombre: 'check', keywords: ['ok', 'listo', 'aprobado'] },
    { emoji: '❌', nombre: 'equis', keywords: ['no', 'error', 'rechazado'] },
    { emoji: '❎', nombre: 'equis boton', keywords: ['no', 'error'] },
    { emoji: '➕', nombre: 'mas', keywords: ['agregar', 'sumar'] },
    { emoji: '➖', nombre: 'menos', keywords: ['quitar', 'restar'] },
    { emoji: '❓', nombre: 'interrogacion', keywords: ['pregunta', 'duda'] },
    { emoji: '❗', nombre: 'exclamacion', keywords: ['alerta', 'importante'] },
    { emoji: '💯', nombre: 'cien', keywords: ['100', 'perfecto'] },
    { emoji: '♻️', nombre: 'reciclar', keywords: ['reciclaje', 'ambiente'] },
    { emoji: '🚮', nombre: 'basura', keywords: ['basura', 'tirar'] },
    { emoji: '🚰', nombre: 'agua', keywords: ['agua', 'potable'] },
    { emoji: '♿', nombre: 'accesible', keywords: ['discapacidad', 'silla'] },
    { emoji: '🚹', nombre: 'hombre', keywords: ['baño', 'hombre'] },
    { emoji: '🚺', nombre: 'mujer', keywords: ['baño', 'mujer'] },
    { emoji: '🚻', nombre: 'baño', keywords: ['baño', 'servicios'] },
    { emoji: '🛂', nombre: 'pasaporte', keywords: ['pasaporte', 'control'] },
    { emoji: '🛃', nombre: 'aduana', keywords: ['aduana', 'control'] },
    { emoji: '🛄', nombre: 'equipaje', keywords: ['maleta', 'viaje'] },
    { emoji: '🛅', nombre: 'consigna', keywords: ['guardar', 'equipaje'] },
    { emoji: '⚠️', nombre: 'advertencia', keywords: ['peligro', 'cuidado'] },
    { emoji: '🚸', nombre: 'ninos', keywords: ['niños', 'cuidado'] },
    { emoji: '🚳', nombre: 'no bicicleta', keywords: ['bici', 'prohibido'] },
    { emoji: '🚭', nombre: 'no fumar', keywords: ['fumar', 'prohibido'] },
    { emoji: '📛', nombre: 'identificacion', keywords: ['nombre', 'etiqueta'] },
    { emoji: '🔞', nombre: '18', keywords: ['adulto', 'prohibido'] },
    { emoji: '☢️', nombre: 'radiacion', keywords: ['peligro', 'nuclear'] },
    { emoji: '☣️', nombre: 'biopeligro', keywords: ['peligro', 'virus'] },
    { emoji: '⬆️', nombre: 'arriba', keywords: ['subir', 'flecha'] },
    { emoji: '⬇️', nombre: 'abajo', keywords: ['bajar', 'flecha'] },
    { emoji: '⬅️', nombre: 'izquierda', keywords: ['flecha'] },
    { emoji: '➡️', nombre: 'derecha', keywords: ['flecha'] },
    { emoji: '🔃', nombre: 'circular', keywords: ['recargar', 'flecha'] },
    { emoji: '🔄', nombre: 'girar', keywords: ['recargar', 'flecha'] },
    { emoji: '🔙', nombre: 'back', keywords: ['atras', 'volver'] },
    { emoji: '🔚', nombre: 'end', keywords: ['fin', 'final'] },
    { emoji: '🔛', nombre: 'on', keywords: ['encendido', 'activo'] },
    { emoji: '🔜', nombre: 'soon', keywords: ['pronto', 'proximo'] },
    { emoji: '🔝', nombre: 'top', keywords: ['arriba', 'superior'] },
  ],
  musica: [
    { emoji: '🎵', nombre: 'nota', keywords: ['musica', 'cancion'] },
    { emoji: '🎶', nombre: 'notas', keywords: ['musica', 'cancion'] },
    { emoji: '🎼', nombre: 'partitura', keywords: ['musica'] },
    { emoji: '🎤', nombre: 'microfono', keywords: ['cantar', 'voz'] },
    { emoji: '🎧', nombre: 'audifonos', keywords: ['musica', 'escuchar'] },
    { emoji: '📻', nombre: 'radio', keywords: ['radio', 'musica'] },
    { emoji: '🎷', nombre: 'saxofon', keywords: ['saxo', 'jazz'] },
    { emoji: '🎸', nombre: 'guitarra', keywords: ['guitarra', 'rock'] },
    { emoji: '🎹', nombre: 'piano', keywords: ['piano', 'musica'] },
    { emoji: '🎺', nombre: 'trompeta', keywords: ['trompeta'] },
    { emoji: '🎻', nombre: 'violin', keywords: ['violin'] },
    { emoji: '🪕', nombre: 'banjo', keywords: ['banjo'] },
    { emoji: '🥁', nombre: 'tambor', keywords: ['bateria', 'percusion'] },
    { emoji: '🪘', nombre: 'djembe', keywords: ['tambor', 'africa'] },
    { emoji: '🎬', nombre: 'claqueta', keywords: ['cine', 'pelicula'] },
    { emoji: '🎥', nombre: 'camara', keywords: ['video', 'filmar'] },
    { emoji: '📽️', nombre: 'proyector', keywords: ['cine', 'pelicula'] },
    { emoji: '🎞️', nombre: 'rollo', keywords: ['foto', 'pelicula'] },
    { emoji: '📺', nombre: 'tv', keywords: ['television'] },
    { emoji: '📸', nombre: 'camara flash', keywords: ['foto'] },
    { emoji: '📷', nombre: 'camara', keywords: ['foto'] },
    { emoji: '📹', nombre: 'camcorder', keywords: ['video'] },
    { emoji: '📼', nombre: 'cinta', keywords: ['video', 'vhs'] },
    { emoji: '🔦', nombre: 'linterna', keywords: ['luz'] },
    { emoji: '🏮', nombre: 'linterna papel', keywords: ['japones', 'luz'] },
    { emoji: '🪔', nombre: 'lampara', keywords: ['luz', 'india'] },
    { emoji: '📯', nombre: 'corno', keywords: ['trompa', 'postal'] },
    { emoji: '🎙️', nombre: 'microfono estudio', keywords: ['radio', 'voz'] },
    { emoji: '🎚️', nombre: 'fader', keywords: ['audio', 'volumen'] },
    { emoji: '🎛️', nombre: 'controles', keywords: ['audio', 'mezclador'] },
    { emoji: '🎧', nombre: 'audifonos', keywords: ['musica'] },
    { emoji: '💿', nombre: 'cd', keywords: ['disco', 'musica'] },
    { emoji: '📀', nombre: 'dvd', keywords: ['disco', 'video'] },
    { emoji: '🔊', nombre: 'sonido alto', keywords: ['volumen', 'ruido'] },
    { emoji: '🔉', nombre: 'sonido', keywords: ['volumen', 'medio'] },
    { emoji: '🔈', nombre: 'sonido bajo', keywords: ['volumen', 'bajo'] },
    { emoji: '🔇', nombre: 'mute', keywords: ['silencio', 'mudo'] },
    { emoji: '👁️', nombre: 'ojo', keywords: ['ver', 'mirar'] },
    { emoji: '👁️‍🗨️', nombre: 'ojo burbuja', keywords: ['ver'] },
  ],
};

let activePicker: { el: HTMLDivElement; destroy: () => void } | null = null;

export function openEmojiPicker(triggerEl: Element, onSelect: (emoji: string) => void) {
  if (activePicker) {
    activePicker.destroy();
    activePicker = null;
  }

  const popover = document.createElement('div');
  popover.className = 'emoji-picker-popover';

  const searchInput = document.createElement('input');
  searchInput.type = 'text';
  searchInput.className = 'emoji-picker-search';
  searchInput.placeholder = 'Buscar icono...';

  const tabsDiv = document.createElement('div');
  tabsDiv.className = 'emoji-picker-tabs';

  const gridDiv = document.createElement('div');
  gridDiv.className = 'emoji-picker-grid';

  let selectedCategory = categorias[0].id;
  let allEmojiEntries: { emoji: string; nombre: string; keywords: string[]; categoria: string }[] = [];
  for (const cat of categorias) {
    for (const e of (emojis[cat.id] || [])) {
      allEmojiEntries.push({ ...e, categoria: cat.id });
    }
  }

  function renderGrid(category: string, search: string) {
    gridDiv.innerHTML = '';
    let items = search
      ? allEmojiEntries.filter(e => {
          const q = search.toLowerCase();
          return e.nombre.includes(q) || e.keywords.some(k => k.includes(q));
        })
      : allEmojiEntries.filter(e => e.categoria === category);

    if (items.length === 0) {
      gridDiv.innerHTML = '<div class="emoji-picker-empty">Sin resultados</div>';
      return;
    }

    for (const item of items) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'emoji-picker-option';
      btn.textContent = item.emoji;
      btn.title = item.nombre;
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        onSelect(item.emoji);
        destroy();
      });
      gridDiv.appendChild(btn);
    }
  }

  function renderTabs(selected: string) {
    tabsDiv.innerHTML = '';
    for (const cat of categorias) {
      const tab = document.createElement('button');
      tab.type = 'button';
      tab.className = `emoji-picker-tab${cat.id === selected ? ' active' : ''}`;
      tab.textContent = cat.icono;
      tab.title = cat.label;
      tab.addEventListener('click', () => {
        selectedCategory = cat.id;
        searchInput.value = '';
        renderTabs(selectedCategory);
        renderGrid(selectedCategory, '');
      });
      tabsDiv.appendChild(tab);
    }
  }

  searchInput.addEventListener('input', () => {
    renderGrid(selectedCategory, searchInput.value);
  });

  renderTabs(selectedCategory);
  renderGrid(selectedCategory, '');

  popover.appendChild(searchInput);
  popover.appendChild(tabsDiv);
  popover.appendChild(gridDiv);
  document.body.appendChild(popover);

  function position() {
    const triggerRect = triggerEl.getBoundingClientRect();
    const popHeight = popover.offsetHeight || 400;
    const popWidth = popover.offsetWidth || 320;

    let top = triggerRect.bottom + 4;
    if (top + popHeight > window.innerHeight) {
      top = triggerRect.top - popHeight - 4;
    }
    let left = Math.max(4, Math.min(triggerRect.left, window.innerWidth - popWidth - 4));
    popover.style.top = `${top}px`;
    popover.style.left = `${left}px`;
  }

  requestAnimationFrame(position);

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') destroy();
  }
  document.addEventListener('keydown', onKeyDown);

  function onClickOutside(e: MouseEvent) {
    if (!popover.contains(e.target as Node) && e.target !== triggerEl) {
      destroy();
    }
  }
  document.addEventListener('mousedown', onClickOutside);

  function destroy() {
    popover.remove();
    document.removeEventListener('keydown', onKeyDown);
    document.removeEventListener('mousedown', onClickOutside);
    if (activePicker?.el === popover) activePicker = null;
  }

  activePicker = { el: popover, destroy };

  searchInput.focus();
}
